name: PostBits
version: '${version}'
main: com.github.postyizhan.PostBits
api-version: '1.13'
description: 'A modular Minecraft plugin with various small features'
authors: [postyizhan]
website: 'https://github.com/postyizhan/PostBits'
softdepend: [ProtocolLib, CraftEngine, ItemsAdder, Oraxen]

commands:
  postbits:
    description: 'PostBits main command'
    usage: '/postbits [reload|update]'
    aliases: [pb]
  heal:
    description: 'Heal yourself'
    usage: '/heal'
  suicide:
    description: 'Commit suicide'
    usage: '/suicide'
  fix:
    description: 'Fix item durability'
    usage: '/fix'
  hat:
    description: 'Wear item as hat'
    usage: '/hat [remove]'
  speed:
    description: 'Change movement speed'
    usage: '/speed <1-10> [walk|fly]'
  fly:
    description: 'Toggle fly mode'
    usage: '/fly [on|off]'
  vanish:
    description: 'Toggle invisibility'
    usage: '/vanish'

permissions:
  postbits.admin:
    description: 'Access to all PostBits admin commands'
    default: op
    children:
      postbits.admin.reload: true
      postbits.admin.update: true
  postbits.admin.reload:
    description: 'Permission to reload the plugin'
    default: op
  postbits.admin.update:
    description: 'Permission to check for updates'
    default: op
  postbits.chair:
    description: 'Access to all chair functions'
    default: op
    children:
      postbits.chair.sit: true
  postbits.chair.sit:
    description: 'Permission to sit on blocks'
    default: true
  postbits.invedit:
    description: 'Access to all inventory edit functions'
    default: op
    children:
      postbits.invedit.use: true
  postbits.invedit.use:
    description: 'Permission to edit player inventories'
    default: op
  postbits.elevator:
    description: 'Access to all elevator functions'
    default: op
    children:
      postbits.elevator.use: true
  postbits.elevator.use:
    description: 'Permission to use elevators'
    default: op
  postbits.utility:
    description: 'Access to all utility commands'
    default: op
    children:
      postbits.utility.heal: true
      postbits.utility.suicide: true
      postbits.utility.fix: true
      postbits.utility.hat: true
      postbits.utility.speed: true
      postbits.utility.fly: true
      postbits.utility.vanish: true
  postbits.utility.heal:
    description: 'Permission to use /heal'
    default: op
  postbits.utility.suicide:
    description: 'Permission to use /suicide'
    default: true
  postbits.utility.fix:
    description: 'Permission to use /fix'
    default: op
  postbits.utility.hat:
    description: 'Permission to use /hat'
    default: op
  postbits.utility.speed:
    description: 'Permission to use /speed'
    default: op
  postbits.utility.fly:
    description: 'Permission to use /fly'
    default: op
  postbits.utility.vanish:
    description: 'Permission to use /vanish'
    default: op
  postbits.utility.vanish.see:
    description: 'Permission to see vanished players'
    default: op
  postbits.portabletools:
    description: 'Access to all portable tools'
    default: op
    children:
      postbits.portabletools.craft: true
      postbits.portabletools.grindstone: true
      postbits.portabletools.cartography: true
      postbits.portabletools.enchanting: true
      postbits.portabletools.smithing: true
      postbits.portabletools.enderchest: true
  postbits.portabletools.craft:
    description: 'Permission to use portable craft table'
    default: op
  postbits.portabletools.grindstone:
    description: 'Permission to use portable grindstone'
    default: op
  postbits.portabletools.cartography:
    description: 'Permission to use portable cartography table'
    default: op
  postbits.portabletools.enchanting:
    description: 'Permission to use portable enchanting table'
    default: op
  postbits.portabletools.smithing:
    description: 'Permission to use portable smithing table'
    default: op
  postbits.portabletools.enderchest:
    description: 'Permission to use portable enderchest'
    default: op
