name: PostBits
version: '${version}'
main: com.github.postyizhan.PostBits
api-version: '1.13'
description: 'A modular Minecraft plugin with various small features'
authors: [postyizhan]
website: 'https://github.com/postyizhan/PostBits'

commands:
  postbits:
    description: 'PostBits main command'
    usage: '/postbits [reload|update]'
    aliases: [pb]

permissions:
  postbits.admin:
    description: 'Access to all PostBits admin commands'
    default: op
    children:
      postbits.admin.reload: true
      postbits.admin.update: true
  postbits.admin.reload:
    description: 'Permission to reload the plugin'
    default: op
  postbits.admin.update:
    description: 'Permission to check for updates'
    default: op
  postbits.chair:
    description: 'Access to all chair functions'
    default: op
    children:
      postbits.chair.sit: true
      postbits.chair.info: true
  postbits.chair.sit:
    description: 'Permission to sit on blocks'
    default: op
  postbits.chair.info:
    description: 'Permission to view seat information'
    default: op
  postbits.invedit:
    description: 'Access to all inventory edit functions'
    default: op
    children:
      postbits.invedit.use: true
  postbits.invedit.use:
    description: 'Permission to edit player inventories'
    default: op
  postbits.elevator:
    description: 'Access to all elevator functions'
    default: op
    children:
      postbits.elevator.use: true
  postbits.elevator.use:
    description: 'Permission to use elevators'
    default: op
